backend:
    name: git-gateway
    branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
    - name: "pages"
      label: "Pages"
      files:
          - label: "Home"
            name: "home"
            file: "content/home.md"
    - name: "resources"
      label: "Resources"
      folder: "_resources"
      create: true
      fields:
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Description"
            name: "desc"
            widget: "markdown"
          - label: "Phone Number"
            name: "phone_no"
            widget: "string"
          - label: "Website"
            name: "website"
            widget: "string"
          - label: "Address"
            name: "address"
            widget: "text"
          - label: "Type"
            name: "type"
            widget: "select"
            options:
                - { label: "Food Assistance", value: "food_assistance" }
                - { label: "Education", value: "education" }
                - { label: "Clothing", value: "clothing" }
                - { label: "Transportation", value: "transportation" }
                - { label: "Housing", value: "housing" }
                - { label: "Mental Health", value: "mental_health" }
                - { label: "Medical", value: "medical" }
                - { label: "Other Services", value: "other_services" }
