backend:
    name: git-gateway
    branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
publish_mode: editorial_workflow
collections:
    - name: "pages"
      label: "Pages"
      label_singular: "Page"
      files:
          - label: "Home"
            name: "home"
            file: "content/pages/home.md"
            fields:
                - { label: "Title", name: "title", widget: "string" }
                - { label: "Publish Date", name: "date", widget: "datetime" }
                - { label: "Body", name: "body", widget: "markdown" }
          - label: "About Us"
            name: "about-us"
            file: "content/pages/about-us.md"
            fields:
                - { label: "Title", name: "title", widget: "string" }
    - name: "resources"
      label: "Resources"
      label_singular: "Resource"
      folder: "content/resources"
      create: true
      slug: "{{slug}}"
      identifier_field: name
      fields:
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Phone Number"
            name: "phone_no"
            widget: "string"
            required: false
          - label: "Website"
            name: "website"
            widget: "string"
            required: false
          - label: "Address"
            name: "address"
            widget: "text"
            required: false
          - label: "Services"
            name: "services"
            widget: "list"
            summary: '{{fields.type}}'
            fields:
              - label: "Type"
                name: "type"
                widget: "select"
                options:
                    - { label: "Food Assistance", value: "food_assistance" }
                    - { label: "Education", value: "education" }
                    - { label: "Clothing", value: "clothing" }
                    - { label: "Transportation", value: "transportation" }
                    - { label: "Housing", value: "housing" }
                    - { label: "Mental Health", value: "mental_health" }
                    - { label: "Medical", value: "medical" }
                    - { label: "Other Services", value: "other_services" }
              - label: "Description"
                name: "description"
                widget: "markdown"
